// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['WEB_KEY']!,
    appId: '1:90775836694:web:d33c30715625493f5dfd37',
    messagingSenderId: '90775836694',
    projectId: 'red-ecommerce-d9a83',
    authDomain: 'red-ecommerce-d9a83.firebaseapp.com',
    storageBucket: 'red-ecommerce-d9a83.appspot.com',
    measurementId: 'G-MJQ6T1JDXC',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['ANDROID_KEY']!,
    appId: '1:90775836694:android:b6e2d6ff2a5753665dfd37',
    messagingSenderId: '90775836694',
    projectId: 'red-ecommerce-d9a83',
    storageBucket: 'red-ecommerce-d9a83.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['IOS_KEY']!,
    appId: '1:90775836694:ios:7f006b7cf7a35cd35dfd37',
    messagingSenderId: '90775836694',
    projectId: 'red-ecommerce-d9a83',
    storageBucket: 'red-ecommerce-d9a83.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['MACOS_KEY']!,
    appId: '1:90775836694:ios:7f006b7cf7a35cd35dfd37',
    messagingSenderId: '90775836694',
    projectId: 'red-ecommerce-d9a83',
    storageBucket: 'red-ecommerce-d9a83.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static FirebaseOptions windows = FirebaseOptions(
    apiKey: dotenv.env['WINDOWS_KEY']!,
    appId: '1:90775836694:web:6ded6132df3619ca5dfd37',
    messagingSenderId: '90775836694',
    projectId: 'red-ecommerce-d9a83',
    authDomain: 'red-ecommerce-d9a83.firebaseapp.com',
    storageBucket: 'red-ecommerce-d9a83.appspot.com',
    measurementId: 'G-WS1YYN8TT3',
  );
}
