// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: getApiKey('WEB_KEY')!,
    appId: '1:641574119132:web:23aeeecad5120d7a14f619',
    messagingSenderId: '641574119132',
    projectId: 'project-red-9d656',
    authDomain: 'project-red-9d656.firebaseapp.com',
    storageBucket: 'project-red-9d656.appspot.com',
    measurementId: 'G-N6GW3EJKPX',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: getApiKey("ANDROID_KEY")!,
    appId: '1:641574119132:android:4dfdb1310bbf3b0d14f619',
    messagingSenderId: '641574119132',
    projectId: 'project-red-9d656',
    storageBucket: 'project-red-9d656.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: getApiKey("IOS_KEY")!,
    appId: '1:641574119132:ios:fa49951c439f99a114f619',
    messagingSenderId: '641574119132',
    projectId: 'project-red-9d656',
    storageBucket: 'project-red-9d656.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: getApiKey("MACOS_KEY")!,
    appId: '1:641574119132:ios:fa49951c439f99a114f619',
    messagingSenderId: '641574119132',
    projectId: 'project-red-9d656',
    storageBucket: 'project-red-9d656.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static FirebaseOptions windows = FirebaseOptions(
    apiKey: getApiKey("WINDOWS_KEY")!,
    appId: '1:641574119132:web:b425390f577a8b9d14f619',
    messagingSenderId: '641574119132',
    projectId: 'project-red-9d656',
    authDomain: 'project-red-9d656.firebaseapp.com',
    storageBucket: 'project-red-9d656.appspot.com',
    measurementId: 'G-6BY2BH05LK',
  );
}

String? getApiKey(String key) {
  String? value = dotenv.env[key];
  // print("$key: $value");
  return value;
}
